create table public.order_statuses (
  key varchar(32) primary key,
  label varchar(64) not null,
  sort_order integer not null unique,
  color varchar(24) not null default 'neutral',
  is_terminal boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz(6) not null default now(),
  updated_at timestamptz(6) not null
);

create table public.siigo_products (
  id uuid primary key,
  code varchar(100) not null,
  name text not null,
  account_group_id integer,
  account_group_name text,
  type varchar(64),
  stock_control boolean,
  active boolean,
  tax_included boolean,
  unit_code varchar(32),
  unit_name text,
  key_code varchar(32),
  key_name text,
  reference text,
  description text,
  barcode text,
  brand text,
  available_quantity numeric(20, 6),
  siigo_created_at timestamptz(6),
  siigo_updated_at timestamptz(6),
  raw_payload jsonb not null,
  synced_at timestamptz(6) not null default now(),
  created_at timestamptz(6) not null default now(),
  updated_at timestamptz(6) not null
);

create index siigo_products_code_idx on public.siigo_products (code);
create index siigo_products_name_idx on public.siigo_products (name);

create table public.siigo_product_prices (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.siigo_products(id) on delete cascade on update cascade,
  currency_code varchar(3) not null,
  position integer not null,
  name text,
  value numeric(20, 6) not null,
  raw_payload jsonb not null,
  unique (product_id, currency_code, position)
);

create table public.siigo_product_taxes (
  product_id uuid not null references public.siigo_products(id) on delete cascade on update cascade,
  siigo_tax_id integer not null,
  name text,
  type varchar(32),
  percentage numeric(9, 6),
  raw_payload jsonb not null,
  primary key (product_id, siigo_tax_id)
);

create table public.siigo_product_warehouses (
  product_id uuid not null references public.siigo_products(id) on delete cascade on update cascade,
  siigo_warehouse_id integer not null,
  name text,
  quantity numeric(20, 6),
  raw_payload jsonb not null,
  primary key (product_id, siigo_warehouse_id)
);

create table public.siigo_product_components (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.siigo_products(id) on delete cascade on update cascade,
  siigo_component_id text,
  name text,
  quantity numeric(20, 6),
  raw_payload jsonb not null
);

create index siigo_product_components_product_id_idx
  on public.siigo_product_components (product_id);

create table public.siigo_customers (
  id uuid primary key,
  name jsonb not null,
  display_name text not null,
  person_type varchar(32),
  type varchar(32),
  identification text,
  rfc_id text,
  fiscal_regime text,
  active boolean,
  address_street text,
  address_interior_number text,
  address_exterior_number text,
  address_colony text,
  address_locality text,
  address_city_name text,
  address_state_name text,
  address_postal_code text,
  raw_payload jsonb not null,
  synced_at timestamptz(6) not null default now(),
  created_at timestamptz(6) not null default now(),
  updated_at timestamptz(6) not null
);

create index siigo_customers_display_name_idx on public.siigo_customers (display_name);
create index siigo_customers_rfc_id_idx on public.siigo_customers (rfc_id);

create table public.siigo_customer_phones (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.siigo_customers(id) on delete cascade on update cascade,
  position integer not null,
  number text,
  raw_payload jsonb not null,
  unique (customer_id, position)
);

create table public.siigo_customer_contacts (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.siigo_customers(id) on delete cascade on update cascade,
  position integer not null,
  first_name text,
  last_name text,
  email text,
  phone text,
  raw_payload jsonb not null,
  unique (customer_id, position)
);

create table public.sales_orders (
  id uuid primary key default gen_random_uuid(),
  folio integer generated by default as identity unique,
  status_key varchar(32) not null default 'borrador'
    references public.order_statuses(key) on delete restrict on update cascade,
  customer_id uuid not null references public.siigo_customers(id) on delete restrict on update cascade,
  customer_name_snapshot text not null,
  customer_rfc_snapshot text,
  customer_payload jsonb not null,
  order_date date not null default current_date,
  promised_date date,
  observations text,
  currency_code varchar(3) not null default 'MXN',
  subtotal numeric(20, 6) not null default 0,
  discount_total numeric(20, 6) not null default 0,
  tax_total numeric(20, 6) not null default 0,
  total numeric(20, 6) not null default 0,
  siigo_reference text,
  registered_in_siigo_at timestamptz(6),
  created_by_name text not null,
  created_by_email text not null,
  created_by_role varchar(32) not null,
  updated_by_email text not null,
  version integer not null default 1,
  created_at timestamptz(6) not null default now(),
  updated_at timestamptz(6) not null,
  constraint sales_orders_totals_nonnegative check (
    subtotal >= 0 and discount_total >= 0 and tax_total >= 0 and total >= 0
  ),
  constraint sales_orders_version_positive check (version > 0)
);

create index sales_orders_status_key_order_date_idx
  on public.sales_orders (status_key, order_date);
create index sales_orders_customer_id_order_date_idx
  on public.sales_orders (customer_id, order_date);
create index sales_orders_created_at_idx on public.sales_orders (created_at);

create table public.sales_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.sales_orders(id) on delete cascade on update cascade,
  position integer not null,
  product_id uuid not null references public.siigo_products(id) on delete restrict on update cascade,
  product_code_snapshot text not null,
  product_name_snapshot text not null,
  product_description_snapshot text,
  product_reference_snapshot text,
  unit_code_snapshot text,
  unit_name_snapshot text,
  product_payload jsonb not null,
  quantity numeric(20, 6) not null,
  unit_price numeric(20, 6) not null,
  discount_percentage numeric(9, 6) not null default 0,
  discount_amount numeric(20, 6) not null default 0,
  tax_payload jsonb not null,
  subtotal numeric(20, 6) not null,
  tax_amount numeric(20, 6) not null default 0,
  total numeric(20, 6) not null,
  created_at timestamptz(6) not null default now(),
  unique (order_id, position),
  constraint sales_order_items_position_positive check (position > 0),
  constraint sales_order_items_quantity_positive check (quantity > 0),
  constraint sales_order_items_amounts_nonnegative check (
    unit_price >= 0
    and discount_percentage between 0 and 100
    and discount_amount >= 0
    and subtotal >= 0
    and tax_amount >= 0
    and total >= 0
  )
);

create index sales_order_items_product_id_idx
  on public.sales_order_items (product_id);

create table public.sales_order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.sales_orders(id) on delete cascade on update cascade,
  from_status_key varchar(32)
    references public.order_statuses(key) on delete restrict on update cascade,
  to_status_key varchar(32) not null
    references public.order_statuses(key) on delete restrict on update cascade,
  note text,
  changed_by_name text not null,
  changed_by_email text not null,
  changed_by_role varchar(32) not null,
  changed_at timestamptz(6) not null default now()
);

create index sales_order_status_history_order_id_changed_at_idx
  on public.sales_order_status_history (order_id, changed_at);

insert into public.order_statuses
  (key, label, sort_order, color, is_terminal, updated_at)
values
  ('borrador', 'Borrador', 10, 'neutral', false, now()),
  ('ingresado', 'Ingresado', 20, 'info', false, now()),
  ('confirmado', 'Confirmado', 30, 'primary', false, now()),
  ('surtido', 'Surtido', 40, 'success', false, now()),
  ('en_espera', 'En espera', 50, 'warning', false, now()),
  ('en_camino', 'En camino', 60, 'info', false, now()),
  ('entregado', 'Entregado', 70, 'success', true, now()),
  ('facturado', 'Facturado', 80, 'primary', true, now()),
  ('cancelado', 'Cancelado', 90, 'error', true, now());

alter table public.order_statuses enable row level security;
alter table public.siigo_products enable row level security;
alter table public.siigo_product_prices enable row level security;
alter table public.siigo_product_taxes enable row level security;
alter table public.siigo_product_warehouses enable row level security;
alter table public.siigo_product_components enable row level security;
alter table public.siigo_customers enable row level security;
alter table public.siigo_customer_phones enable row level security;
alter table public.siigo_customer_contacts enable row level security;
alter table public.sales_orders enable row level security;
alter table public.sales_order_items enable row level security;
alter table public.sales_order_status_history enable row level security;

revoke all on table
  public.order_statuses,
  public.siigo_products,
  public.siigo_product_prices,
  public.siigo_product_taxes,
  public.siigo_product_warehouses,
  public.siigo_product_components,
  public.siigo_customers,
  public.siigo_customer_phones,
  public.siigo_customer_contacts,
  public.sales_orders,
  public.sales_order_items,
  public.sales_order_status_history
from anon, authenticated;

revoke all on sequence
  public.siigo_product_prices_id_seq,
  public.siigo_product_components_id_seq,
  public.siigo_customer_phones_id_seq,
  public.siigo_customer_contacts_id_seq,
  public.sales_orders_folio_seq,
  public.sales_order_status_history_id_seq
from anon, authenticated;
