alter table public.sales_order_items
  add column tax_included boolean not null default false;

create table public.sales_order_item_price_history (
  id bigint generated by default as identity primary key,
  order_item_id uuid not null references public.sales_order_items(id) on delete cascade on update cascade,
  order_id uuid not null references public.sales_orders(id) on delete cascade on update cascade,
  previous_price numeric(20, 6) not null,
  new_price numeric(20, 6) not null,
  note text,
  changed_by_name text not null,
  changed_by_email text not null,
  changed_by_role varchar(32) not null,
  changed_at timestamptz(6) not null default now(),
  constraint sales_order_item_price_history_prices_nonnegative check (
    previous_price >= 0 and new_price >= 0
  )
);

create index sales_order_item_price_history_order_item_id_changed_at_idx
  on public.sales_order_item_price_history (order_item_id, changed_at);
create index sales_order_item_price_history_order_id_changed_at_idx
  on public.sales_order_item_price_history (order_id, changed_at);

alter table public.sales_order_item_price_history enable row level security;

revoke all on table public.sales_order_item_price_history from anon, authenticated;
revoke all on sequence public.sales_order_item_price_history_id_seq from anon, authenticated;
